### ISSUE TITLE
Using LoWe as a remote desktop client for Linux machines?

### ISSUE THREAD

**Issue by kuza55** [kpocza/LoWe#1]
Hey,

I was wondering if you had any thoughts on whether LoWe would be a good fit for running GUI apps on remote Linux systems from Windows?

**Comment by kpocza** [comment]
It's not supported to directly run LoWeAgent on the remove Linux and run LoWeExposer on the local Windows system.

But:
If you first start the local X server with wmaker using LoWe as described in the documentation and you ssh -X to that system from a local xterm (or from bash where DISPLAY is exported) then it runs.
You must ensure that X11Forwarding is enabled in the sshd_config on the remote Linux system.

See screenshot:
![removex](https://cloud.githubusercontent.com/assets/6399280/20031628/eaf805ca-a37a-11e6-9213-943dbdc24e89.jpg)
