### ISSUE TITLE
Question) Change the names of some files to lowercase

### ISSUE THREAD

**Issue by j2doll** [kpocza/LoWe#10]
Dear @kpocza
In my opinion, you should change the names of some files to lowercase as follows:

- before
```
LoWe/src/LoWeExposer/LoWeExposer/
ALSAExposer.xaml
ALSAExposer.xaml.cs
```

- after
```
LoWe/src/LoWeExposer/LoWeExposer/
AlsaExposer.xaml
AlsaExposer.xaml.cs
```

**Comment by kpocza** [comment]
@j2doll 

Could you please clarify where you see ALSAExposer with all capitals in ALSA? When I view the respective folder in Total Commander or run ls I see the following:
+++
kpocza@AVANTASIA:/mnt/c/Prog/LoWe/src/LoWeExposer/LoWeExposer$ ls
AlsaExposer.xaml     bin                         KbdExposer.xaml.cs      MiceExposer.xaml     String2KeyEventConverter.cs
AlsaExposer.xaml.cs  FrameBufferExposer.xaml     LoWeExposer.csproj      MiceExposer.xaml.cs
App.config           FrameBufferExposer.xaml.cs  MainWindowViewModel.cs  obj
App.xaml             Handlers                    MainWindow.xaml         packages.config
App.xaml.cs          KbdExposer.xaml             MainWindow.xaml.cs      Properties
+++

For me everything looks nice.

**Comment by j2doll** [comment]
Dear @kpocza

I tested it in the following environment.

- Test Environment
	- Visual Studio 2017 x64 (ver 15.8.9)
	- Microsoft Windows 10 x64 (ver 1803 build 17134.407)

- Visual Studio Error List
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The project file contains a property value that is not valid.	LoWeExposer			
Error		File 'AlsaExposer.xaml' cannot be found.	LoWeExposer			
Warning		The referenced component 'NAudio' could not be found.	LoWeExposer			
```

- LoWeExposer.csproj consists of the following.
```
...
<Page Include="AlsaExposer.xaml">
  <SubType>Designer</SubType>
  <Generator>MSBuild:Compile</Generator>
</Page>
...
<Compile Include="AlsaExposer.xaml.cs">
  <DependentUpon>AlsaExposer.xaml</DependentUpon>
</Compile>
...    
```

- If I rename the file, the build succeeds.
	- before
	```
	LoWe/src/LoWeExposer/LoWeExposer/
	ALSAExposer.xaml
	ALSAExposer.xaml.cs
	```
	- after
	```
	LoWe/src/LoWeExposer/LoWeExposer/
	AlsaExposer.xaml
	AlsaExposer.xaml.cs
	```

**Comment by kpocza** [comment]
Dear @j2doll,

Now I understand your problem.
I see that GitHub had ALSAExposer while my filesystem has AlsaExposer.
Most probably in the past I renamed these files however git doesn't consider case alteration as a change.
This shouldn't be a problem as NTFS itself is case insensitive by default however this behavior can be changed even at folder level (to support WSL). Maybe you checked out the repository to a case sensitive folder.

I've changed the file names to match the project file references. 
Please pull the changes and inform me.

**Comment by j2doll** [comment]
The build is good.
