### ISSUE TITLE
Getting error "Unable to resolve app config"

### ISSUE THREAD

**Issue by playerdefault** [kpocza/LoWe#12]
When trying to run loweagent, the application does not start.

**Input**
`./loweagent -e libreoffice`

**Output**
```
[INFO]{config}: Config loaded successfully
[INFO]{main}: Determining program mode from exec param: vlc
[INFO]{main}: Main program name is vlc
[ERR]{main}: Unable to resolve app config
```

LoWeExposer is active and enabled on Windows. I had built it using `build.cmd ` using the Developer Command Prompt for VS 2017. The build had completed successfully.

The Windows version is 1803 and Ubuntu version on WSL is 18.04

**Comment by kpocza** [comment]
@playerdefault
You cannot start LibreOffice directly. First your should start X plus a WM. 
Please consider these instructions: https://github.com/kpocza/LoWe/blob/master/docs/x.md
Start LibreOffice in the X environment afterwards.

The respective error message isn't referring to the app.config file (LoWeExposer.exe.config) on the Windows side but the fact the LibreOffice app is not configured for direct execution.

**Comment by playerdefault** [comment]
Ah. Got it. Thanks. But it would be a useful feature to handle opening applications directly instead of opening an X server.

Warm regards,
Swaraj Mohapatra
Member Technical Staff, Dev
First American (India)

________________________________
