### ISSUE TITLE
Unclear what environment is supported by master branch

### ISSUE THREAD

**Issue by CherryDT** [kpocza/LoWe#4]
master's readme says:

> LoWe officially supports Windows 10 Redstone 2 (aka Creators Update) running Ubuntu 16 LTS. If you're still running Windows 10 Anniversary Update with Ubuntu 14 LTS then please checkout w10auu14 branch.
> 
> This branch supports Windows 10 Anniversary Update only with Ubuntu 14 LTS. Windows 10 Creators Update running Ubuntu 16 LTS support is under heavy construction in branch w10rs2u16 which is not fully working yet.

Seems to be conflicting information right next to each other. This is neither `w10auu14` nor `w10rs2u16`, this is `master`, so it is not clear to me what environment is supported by the master branch - CU? AU? both? none? 😕

**Comment by kpocza** [comment]
Thank you for the feedback. 
The 2nd statement has been removed as master supports CU while w10auu14 supports AU. w10rs2u16 was the dev branch for CU that might be decommissioned soon.
