### ISSUE TITLE
Just wanted to make sure

### ISSUE THREAD

**Issue by aphextwins** [kpocza/LoWe#7]
Are you aware of https://github.com/Lumak/VcXsvr
VcXsvr is like xming but better
check it out if you havent already

**Comment by kpocza** [comment]
@aphextwins
Okay, running a full X server on Windows is an other approach that completely differs from the concepts begind LoWe.

**Comment by anthonycote345** [comment]
this issue hasn't had any activity in two months. i believe it should be closed
