### ISSUE TITLE
Will this project ever support graphical applications without having then run in unity?

### ISSUE THREAD

**Issue by empireij** [kpocza/LoWe#9]

**Comment by kpocza** [comment]
I don't know if I understand your question correctly.
LoWe allows you to run X server. Upon X several window managers like Unity, IceWM, etc. are running. 
You will always need a native X server with a window manager running on Ubuntu on Windows coordinated by LoWe to use GUI applications. This is how it works. LoWe is not an X-call interpreter, it emulates Linux kernel syscalls.
I hope I correctly understood your question.
